<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class ShowtimesSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        DB::table('showtimes')->insert([
            [
                'dateTime' => "2022-12-07 12:00:00",
                'hall' => "1",
                'cinemaID' => "2",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 15:00:00",
                'hall' => "1",
                'cinemaID' => "2",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 18:00:00",
                'hall' => "1",
                'cinemaID' => "2",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 21:00:00",
                'hall' => "1",
                'cinemaID' => "2",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 12:00:00",
                'hall' => "2",
                'cinemaID' => "2",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 15:00:00",
                'hall' => "2",
                'cinemaID' => "2",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 18:00:00",
                'hall' => "2",
                'cinemaID' => "2",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 21:00:00",
                'hall' => "2",
                'cinemaID' => "2",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 12:00:00",
                'hall' => "3",
                'cinemaID' => "2",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 15:00:00",
                'hall' => "3",
                'cinemaID' => "2",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 18:00:00",
                'hall' => "3",
                'cinemaID' => "2",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 21:00:00",
                'hall' => "3",
                'cinemaID' => "2",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 12:00:00",
                'hall' => "4",
                'cinemaID' => "2",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 15:00:00",
                'hall' => "4",
                'cinemaID' => "2",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 18:00:00",
                'hall' => "4",
                'cinemaID' => "2",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 21:00:00",
                'hall' => "4",
                'cinemaID' => "2",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 08:00:00",
                'hall' => "1",
                'cinemaID' => "1",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 12:30:00",
                'hall' => "1",
                'cinemaID' => "1",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 15:30:00",
                'hall' => "1",
                'cinemaID' => "1",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 08:00:00",
                'hall' => "2",
                'cinemaID' => "1",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 12:30:00",
                'hall' => "2",
                'cinemaID' => "1",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 15:30:00",
                'hall' => "2",
                'cinemaID' => "1",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 08:00:00",
                'hall' => "3",
                'cinemaID' => "1",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 12:30:00",
                'hall' => "3",
                'cinemaID' => "1",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 15:30:00",
                'hall' => "3",
                'cinemaID' => "1",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 08:00:00",
                'hall' => "4",
                'cinemaID' => "1",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 12:30:00",
                'hall' => "4",
                'cinemaID' => "1",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-07 15:30:00",
                'hall' => "4",
                'cinemaID' => "1",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 12:00:00",
                'hall' => "1",
                'cinemaID' => "2",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 15:00:00",
                'hall' => "1",
                'cinemaID' => "2",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 18:00:00",
                'hall' => "1",
                'cinemaID' => "2",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 21:00:00",
                'hall' => "1",
                'cinemaID' => "2",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 12:00:00",
                'hall' => "2",
                'cinemaID' => "2",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 15:00:00",
                'hall' => "2",
                'cinemaID' => "2",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 18:00:00",
                'hall' => "2",
                'cinemaID' => "2",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 21:00:00",
                'hall' => "2",
                'cinemaID' => "2",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 12:00:00",
                'hall' => "3",
                'cinemaID' => "2",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 15:00:00",
                'hall' => "3",
                'cinemaID' => "2",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 18:00:00",
                'hall' => "3",
                'cinemaID' => "2",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 21:00:00",
                'hall' => "3",
                'cinemaID' => "2",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 12:00:00",
                'hall' => "4",
                'cinemaID' => "2",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 15:00:00",
                'hall' => "4",
                'cinemaID' => "2",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 18:00:00",
                'hall' => "4",
                'cinemaID' => "2",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 21:00:00",
                'hall' => "4",
                'cinemaID' => "2",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 08:00:00",
                'hall' => "1",
                'cinemaID' => "1",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 12:30:00",
                'hall' => "1",
                'cinemaID' => "1",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 15:30:00",
                'hall' => "1",
                'cinemaID' => "1",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 08:00:00",
                'hall' => "2",
                'cinemaID' => "1",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 12:30:00",
                'hall' => "2",
                'cinemaID' => "1",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 15:30:00",
                'hall' => "2",
                'cinemaID' => "1",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 08:00:00",
                'hall' => "3",
                'cinemaID' => "1",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 12:30:00",
                'hall' => "3",
                'cinemaID' => "1",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 15:30:00",
                'hall' => "3",
                'cinemaID' => "1",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 08:00:00",
                'hall' => "4",
                'cinemaID' => "1",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 12:30:00",
                'hall' => "4",
                'cinemaID' => "1",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-09 15:30:00",
                'hall' => "4",
                'cinemaID' => "1",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 12:00:00",
                'hall' => "1",
                'cinemaID' => "2",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 15:00:00",
                'hall' => "1",
                'cinemaID' => "2",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 18:00:00",
                'hall' => "1",
                'cinemaID' => "2",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 21:00:00",
                'hall' => "1",
                'cinemaID' => "2",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 12:00:00",
                'hall' => "2",
                'cinemaID' => "2",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 15:00:00",
                'hall' => "2",
                'cinemaID' => "2",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 18:00:00",
                'hall' => "2",
                'cinemaID' => "2",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 21:00:00",
                'hall' => "2",
                'cinemaID' => "2",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 12:00:00",
                'hall' => "3",
                'cinemaID' => "2",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 15:00:00",
                'hall' => "3",
                'cinemaID' => "2",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 18:00:00",
                'hall' => "3",
                'cinemaID' => "2",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 21:00:00",
                'hall' => "3",
                'cinemaID' => "2",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 12:00:00",
                'hall' => "4",
                'cinemaID' => "2",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 15:00:00",
                'hall' => "4",
                'cinemaID' => "2",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 18:00:00",
                'hall' => "4",
                'cinemaID' => "2",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 21:00:00",
                'hall' => "4",
                'cinemaID' => "2",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 08:00:00",
                'hall' => "1",
                'cinemaID' => "1",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 12:30:00",
                'hall' => "1",
                'cinemaID' => "1",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 15:30:00",
                'hall' => "1",
                'cinemaID' => "1",
                'moviesID' => "1",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 08:00:00",
                'hall' => "2",
                'cinemaID' => "1",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 12:30:00",
                'hall' => "2",
                'cinemaID' => "1",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 15:30:00",
                'hall' => "2",
                'cinemaID' => "1",
                'moviesID' => "2",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 08:00:00",
                'hall' => "3",
                'cinemaID' => "1",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 12:30:00",
                'hall' => "3",
                'cinemaID' => "1",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 15:30:00",
                'hall' => "3",
                'cinemaID' => "1",
                'moviesID' => "3",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 08:00:00",
                'hall' => "4",
                'cinemaID' => "1",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 12:30:00",
                'hall' => "4",
                'cinemaID' => "1",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'dateTime' => "2022-12-10 15:30:00",
                'hall' => "4",
                'cinemaID' => "1",
                'moviesID' => "4",
                'created_at' => Carbon::now()->toDateTimeString(),
            ],
        ]);
    }

}
